import Head from 'next/head';

import type { NextPageContext } from 'next/types';

import Layout from '../components/Layout/Index';

const Home = () => {
  return (
    <div className="min-h-screen flex flex-col justify-between">
      <Head>
        <title>Portfolio - JHG</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="container mx-auto px-4"></div>
      </Layout>
    </div>
  );
};

const getStaticProps = async (context: NextPageContext) => {
  const locale = context.locale;
  const messages = await import(`../translations/${locale}/common.json`);
  return {
    props: {
      messages: messages.default,
    },
  };
};

export { getStaticProps };
export default Home;
