import Head from 'next/head';
import Image from 'next/image';
import Footer from '../components/Layout/Footer';
import Layout from '../components/Layout/Index';

export default function Home() {
  return (
    <div className="min-h-screen flex flex-col justify-between">
      <Head>
        <title>Portfolio - JHG</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="container mx-auto px-4"></div>
      </Layout>
    </div>
  );
}
