import { render } from "@react-email/render";
import { writeFileSync, mkdirSync } from "fs";
import CvDeliveryEmail from "./src/cv-delivery-email";
import ContactNotificationEmail from "./src/contact-notification-email";
import ResetPasswordEmail from "./src/reset-password-email";
import TwoFactorOtpEmail from "./src/two-factor-otp-email";
import type { Locale } from "./src/load-messages";

const locales: Locale[] = ["en", "es", "nl"];

async function main() {
  mkdirSync("./out", { recursive: true });

  const templates: Record<string, string> = {};

  for (const locale of locales) {
    // 1. CV Delivery
    const cvHtmlPreview = await render(
      await CvDeliveryEmail({ recipientName: "John Lennon", locale }),
      { pretty: true },
    );
    writeFileSync(`./out/cv-delivery-${locale}-preview.html`, cvHtmlPreview);

    const cvHtmlTemplate = await render(
      await CvDeliveryEmail({ recipientName: "{{{RECIPIENT_NAME}}}", locale }),
      { pretty: false },
    );
    templates[`cv-delivery-${locale}`] = cvHtmlTemplate;

    // 2. Contact Notification
    const contactHtmlPreview = await render(
      await ContactNotificationEmail({
        senderName: "hello world",
        senderEmail: "visitor@example.com",
        message:
          "Hola amigo, quisiera un nuevo servicio y tengo una nueva idea donde me puedes colaborar.",
        sentAt: "Jul 22, 2026, 3:41 PM",
        locale,
      }),
      { pretty: true },
    );
    writeFileSync(
      `./out/contact-notification-${locale}-preview.html`,
      contactHtmlPreview,
    );

    const contactHtmlTemplate = await render(
      await ContactNotificationEmail({
        senderName: "{{{SENDER_NAME}}}",
        senderEmail: "{{{SENDER_EMAIL}}}",
        message: "{{{MESSAGE}}}",
        sentAt: "{{{SENT_AT}}}",
        locale,
      }),
      { pretty: false },
    );
    templates[`contact-notification-${locale}`] = contactHtmlTemplate;

    // 3. Reset Password
    const resetHtmlPreview = await render(
      await ResetPasswordEmail({
        resetUrl: "https://jesushg.com/reset-password?token=example",
        locale,
      }),
      { pretty: true },
    );
    writeFileSync(
      `./out/reset-password-${locale}-preview.html`,
      resetHtmlPreview,
    );

    const resetHtmlTemplate = await render(
      await ResetPasswordEmail({
        resetUrl: "{{{RESET_URL}}}",
        locale,
      }),
      { pretty: false },
    );
    templates[`reset-password-${locale}`] = resetHtmlTemplate;

    // 4. Two-factor email OTP
    const otpHtmlPreview = await render(
      await TwoFactorOtpEmail({ otpCode: "123456", locale }),
      { pretty: true },
    );
    writeFileSync(
      `./out/two-factor-otp-${locale}-preview.html`,
      otpHtmlPreview,
    );

    const otpHtmlTemplate = await render(
      await TwoFactorOtpEmail({ otpCode: "{{{OTP_CODE}}}", locale }),
      { pretty: false },
    );
    templates[`two-factor-otp-${locale}`] = otpHtmlTemplate;
  }

  const tsContent = `// Auto-generated by render.tsx in email-templates. Do not edit directly.\nexport const COMPILED_TEMPLATES: Record<string, string> = ${JSON.stringify(templates, null, 2)};\n`;
  writeFileSync("./src/compiled-templates.ts", tsContent);

  console.log(
    "\n✅ All previews written to ./out/ and compiled templates written to ./src/compiled-templates.ts",
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
